services:
  - type: web
    name: vera-bot
    runtime: python
    plan: free
    buildCommand: "echo no dependencies"
    startCommand: "python main.py"
    healthCheckPath: /v1/healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
